spring.application.name=finanzas

spring.datasource.url=jdbc:postgresql://localhost:5432/finanzas
spring.datasource.username=finanzas
spring.datasource.password=finanzas

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
