spring.application.name=finanzas

spring.datasource.url=jdbc:postgresql://localhost:5432/finanzas
spring.datasource.username=finanzas
spring.datasource.password=finanzas

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

tipo-de-cambio.url=https://open.er-api.com/v6
tipo-de-cambio.timeout-conexion=2s
tipo-de-cambio.timeout-lectura=3s
