CREATE TABLE movimientos (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR(120)   NOT NULL,
    monto       NUMERIC(12, 2) NOT NULL CHECK (monto > 0),
    fecha       DATE           NOT NULL
);
